apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml
- ingress.yaml

replacements:
- source:
    fieldPath: metadata.annotations.replacement\.kustomize\.config\.k8s\.io/ingress\.host
    kind: Ingress
    name: demoapp
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: demoapp

images:
- name: ghcr.io/askainet/git-demo
  newTag: 4eb92c037c9dfe05b4a966333db5d13469b4b618
