apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml
- ingress.yaml

replacements:
- source:
    fieldPath: metadata.annotations.replacement\.kustomize\.config\.k8s\.io/ingress\.host
    kind: Ingress
    name: demoapp
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
      name: demoapp
- source:
    fieldPath: metadata.annotations.replacement\.kustomize\.config\.k8s\.io/replicas
    kind: Deployment
    name: demoapp
  targets:
  - fieldPaths:
    - spec.replicas
    select:
      kind: Deployment
      name: demoapp

images:
- name: ghcr.io/askainet/git-demo
  newTag: 070094fdd7bce643304b06afb4354f97dd1dc2eb
