name: ci

on:
  push:

env:
  DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_TAG_CI: ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG_CI }}

      - name: Smoke test
        run: |
          docker network create ci
          docker run -d --network ci --name app -p 80:80 --rm ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG_CI }}
          docker run --rm --network ci curlimages/curl:latest http://app | grep -q "this is important"

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Kubernetes resources
        run: |
          cd kubernetes
          kustomize edit set image ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Update image tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update image tag"
          git push
