name: ci

on:
  push:

env:
  DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_TAG_CI: ci

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG_CI }}

    - name: Smoke test
      run: |
        docker network create ci
        docker run -d --network ci --name app -p 80:80 --rm ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG_CI }}
        curl -v app:80

    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
